# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leslie
title: Full Stack Developer | Marketing Team member
email: lcui20829@gmail.com
website: https://leslie-gitt.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username: Leslie-gitt
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: leslie-cui/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/IMG_4113.JPG
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Leslie, a versatile professional with a Bachelor's degree in Law from Peking University and currently pursuing an SDE program at Centennial College. I'm also awaiting my master's offer from the Georgia Institute of Technology. With hands-on experience as a Full Stack Developer at Vizon and a member of the Marketing team at Forest Hill Real Estate Inc., I bring a unique blend of programming expertise and strong communication skills. I pride myself on being a well-rounded professional, capable of navigating both technical and interpersonal landscapes with ease.
  I am most skilled in: <mark>Csharp, C Language, SQL, React.js, HTML, CSS, Javascript</mark> and <mark>Multi-Language(Korean, Mandarin and English)Translating & Writing</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Real Estate Listing Website
        link: github.com/Leslie-gitt/real-estate-listing
        # link_text: Project Website
        additional_links:
          - title:  Leslie-gitt/real-estate-listing
            icon: fab fa-github
            url: https://github.com/Leslie-gitt/real-estate-listing
        quote: >
          A comprehensive real estate listing platform developed using React.js and Node.js, allowing users to search, filter, and view properties with ease.
        description: | # this will include new lines to allow paragraphs
          This project was part of my internship with Forest Hill Real Estate Inc. It involved developing a user-friendly interface using <mark>React.js</mark> and a backend server with <mark>Node.js</mark> and <mark>Express.js</mark>. I gained valuable experience in full-stack development and integrating third-party APIs.

      - layout: top-middle
        title: E-commerce Website for Local Businesses
        link: github.com/Leslie-gitt/e-commerce-platform
        additional_links:
          - title:  Leslie-gitt/e-commerce-platform
            icon: fab fa-github
            url: https://github.com/Leslie-gitt/e-commerce-platform
        quote: >
          An e-commerce platform built to support local businesses in expanding their online presence and managing sales efficiently.
        description: | # this will include new lines to allow paragraphs
          Developed as a school project at Centennial College, this platform utilizes <mark>SQL</mark> for database management and <mark>React.js</mark> for front-end development. It includes features like product listings, user authentication, and a secure payment gateway.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Forest Hill Real Estate Inc.
        link: foresthill.com
        sub_title: Marketing Team Member & Full Stack Developer
        caption: June 2023 - Present
        quote: >
          Blending technology with real estate marketing to enhance customer experience and streamline property management processes.
        description: | # this will include new lines to allow paragraphs
            At Forest Hill, I work closely with the marketing team to develop digital tools and strategies. My role involves both marketing and development, allowing me to apply my programming skills to create engaging web applications and optimize the company's online presence.

      - layout: left
        title: Vizon
        link: vizon.com
        sub_title: Full Stack Developer Intern
        caption: January 2023 - May 2023
        quote: >
          Contributed to the development of innovative software solutions to optimize client business processes and enhance user experience.
        description: | # this will include new lines to allow paragraphs
            During my internship at Vizon, I was involved in multiple projects, including building internal tools with <mark>React.js</mark> and <mark>Node.js</mark>. I also collaborated with the UI/UX team to enhance user interfaces and ensure responsive designs.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Centennial College
        caption: 2023 - Present
        sub_title: Software Development (SDE) Program
        quote: >
          Centennial College provides a dynamic learning environment for developing practical skills in software engineering, preparing students for careers in technology.
        description: | # this will include new lines to allow paragraphs
          As a student in the SDE program, I have developed a strong foundation in programming and software development. My coursework includes advanced studies in <mark>data structures, algorithms, web development, and database management</mark>. I have also participated in several hackathons and collaborative projects.

      - layout: left
        title: Peking University
        caption: 2015 - 2019
        sub_title: Bachelor of Law
        quote: >
          One of China's most prestigious universities, Peking University provided a comprehensive education in law, focusing on critical thinking and analytical skills.
        description: | # this will include new lines to allow paragraphs
          My law degree has equipped me with strong research, writing, and analytical skills. These skills have been instrumental in my transition into the tech field, allowing me to approach problems from a unique perspective and communicate complex ideas effectively.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Besides my passion for software development and technology, some of my other interests and hobbies include:
      - Traveling and exploring new cultures
      - Cooking and experimenting with new recipes
      - Learning new languages
      - Playing chess and other strategy games

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
