# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Leslie
title: "Full Stack Developer | Marketing Team member"
email: lcui20829@gmail.com
website: https://leslie-gitt.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Leslie-gitt
linkedin_username: leslie-cui/

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
#   - title: another link
#     icon: fab fa-twitter
#     url: https://twitter.com

# Google Analytics and Tag Manager
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Profile.JPG
about_content: |
  Hello, I'm Leslie, a versatile professional with a Bachelor's degree in Law from Peking University and currently pursuing an SDE program at Centennial College. I'm also awaiting my master's offer from the Georgia Institute of Technology. With hands-on experience as a Full Stack Developer at Vizon and a member of the Marketing team at Forest Hill Real Estate Inc., I bring a unique blend of programming expertise and strong communication skills. I pride myself on being a well-rounded professional, capable of navigating both technical and interpersonal landscapes with ease.
  I am most skilled in: <mark>Csharp, C Language, SQL, React.js, HTML, CSS, Javascript</mark> and <mark>Multi-Language(Korean, Mandarin and English) Critical Thinking & Writing, Translating</mark>.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Vizon Webpage
        link: www.vizongroup.com
        quote: >
          A company website for Vizon is being developed using the same tech stack of React.js and Node.js. The website will support users in searching, filtering, sending requests, and contacting the backend. (under development)
        description: |
          This project was part of my internship with Vizon. It involved developing a user-friendly interface using <mark>React.js</mark> and a backend server with <mark>Node.js</mark>. I gained valuable experience in full-stack development and integrating third-party APIs. Which haven't been shown is Vizon Database and Real Vizon Database.

      - layout: top-middle
        title: College Projects
        link: http://studentweb.cencol.ca/lcui18/
        quote: >
          A series of classroom projects were completed by learning and using HTML, CSS, and JavaScript.
        description: |
          Successfully completed the assignments given by the instructor, demonstrating a solid understanding and application of <mark> HTML, CSS, and JavaScript</mark>, which earned high praise from the instructor. Additionally, <mark> my aesthetic choices, including webpage layout, color scheme, and font selection</mark>, were well-received and recognized for their quality.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Forest Hill Real Estate Inc.
        link: https://www.bellaleegroup.com
        sub_title: Marketing Team Member 
        caption: Aug. 2024 - Present
        quote: >
          Blending technology with real estate marketing to enhance customer experience and streamline property management processes.
        description: |
          Conduct comprehensive property research to <mark> craft compelling and market-savvy advertisements </mark> that captivate potential buyers; <mark> Design and produce visually stunning promotional materials <mark>, including posters and digital content, to elevate brand presence; Strategically manage social media platforms to enhance engagement and drive customer interest through targeted campaigns.

      - layout: left
        title: Vizon
        link: vizon.com
        sub_title: Full Stack Developer Intern
        caption: Feb. 2024 - Aug. 2024
        quote: >
          Contributed to the development of innovative software solutions to optimize client business processes and enhance user experience.
        description: |
          Participated in <mark> designing the UI prototype of the AI study abroad system using Figma </mark>, which streamlined the development process and revised 3 versions of UI; Developed frontend pages as the main developer with <mark>React.js and Material UI library</mark>, resulting in a 25% increase in user engagement due to enhanced responsiveness; Collaborated and worked with the backend team to <mark>integrate more than 5 APIs using Node.js</mark>, leading to faster and more reliable system performance; Designed and implemented data scraping and data cleaning processes using <mark> Python, Numpy and Pandas</mark>, reducing data inconsistencies by around 30% and ensuring high-quality data for the AI system; Contributed to <mark> the design of a relational database</mark>, supporting scalable data storage for future system expansion to NoSQL database.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Centennial College
        caption: Jan. 2024 - Present
        sub_title: Software Engineering Technology
        link: https://www.centennialcollege.ca
        quote: >
          Centennial College provides a dynamic learning environment for developing practical skills in software engineering, preparing students for careers in technology.
        description: |
          As a student in the SET program, I have cultivated a robust foundation in programming and software development. My academic journey encompasses in-depth studies in <mark>C# (including Object-Oriented Programming), HTML, CSS, JavaScript, Unix, and SQL, focusing on data structures, algorithms, web development, back-end development, and database management.</mark> Additionally, I have actively participated in numerous hackathons and collaborative projects, further enhancing my skills and practical experience.

      - layout: left
        title: Peking University
        caption: 2018 - 2023
        sub_title: Bachelor of Law
        link: https://www.pku.edu.cn
        quote: >
          Studying in China's Best universities (QS17), Peking University provided a comprehensive education in law, focusing on critical thinking and analytical skills.
        description: |
          My law degree has equipped me with strong research, writing, and analytical skills. These skills have been instrumental in my transition into the tech field, allowing me to approach problems from a unique perspective and communicate complex ideas effectively.

  - title: A Little More About Me
    layout: text
    content: |
      Besides my passion for software development and technology, some of my other interests and hobbies include:
      - Learning new languages
      - Cooking and experimenting with new recipes
      - Traveling and exploring new cultures
      - Playing chess and other strategy games

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
